
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author moham
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form salesTaxes
     */
    public Main() {
        initComponents();
        CreateDb();
        Create_goods_table();
        initialize_goods_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProducts = new javax.swing.JPanel();
        jbtnCD = new javax.swing.JButton();
        jbtnBook = new javax.swing.JButton();
        jbtnChocolateBar = new javax.swing.JButton();
        jbtnChocolateBox = new javax.swing.JButton();
        jbtnOil = new javax.swing.JButton();
        jbtnCola = new javax.swing.JButton();
        jbtnHeadachePills = new javax.swing.JButton();
        jbtnColaBox = new javax.swing.JButton();
        jbtnBottleOfPerfume = new javax.swing.JButton();
        jbtnImportedBottleOfPerfume = new javax.swing.JButton();
        jbtnImportedHeadachePills = new javax.swing.JButton();
        jbtnImportedOil = new javax.swing.JButton();
        jbtnImportedColaBox = new javax.swing.JButton();
        jbtnImportedChocolateBox = new javax.swing.JButton();
        jbtnImportedBooks = new javax.swing.JButton();
        jLabelImportedGoods = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReceipt = new javax.swing.JTable();
        jPanelOperation = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jPanelResult = new javax.swing.JPanel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelSalesTaxes = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jTextFieldSalesTax = new javax.swing.JTextField();
        jLabelReceipt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelProducts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanelProducts.setForeground(new java.awt.Color(242, 242, 242));
        jPanelProducts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnCD.setText("CD");
        jbtnCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCDActionPerformed(evt);
            }
        });
        jPanelProducts.add(jbtnCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 190, 40));

        jbtnBook.setText("Book");
        jPanelProducts.add(jbtnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 170, 40));

        jbtnChocolateBar.setText("Chocolate Bar");
        jPanelProducts.add(jbtnChocolateBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 40));

        jbtnChocolateBox.setText("Chocolate Box");
        jPanelProducts.add(jbtnChocolateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, 40));

        jbtnOil.setText("Oil");
        jPanelProducts.add(jbtnOil, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 170, 40));

        jbtnCola.setText("Cola");
        jbtnCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnColaActionPerformed(evt);
            }
        });
        jPanelProducts.add(jbtnCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 190, 40));

        jbtnHeadachePills.setText("Headache Pills");
        jPanelProducts.add(jbtnHeadachePills, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, 40));

        jbtnColaBox.setText("Cola Box");
        jbtnColaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnColaBoxActionPerformed(evt);
            }
        });
        jPanelProducts.add(jbtnColaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 190, 40));

        jbtnBottleOfPerfume.setText("Bottle of Perfume");
        jbtnBottleOfPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBottleOfPerfumeActionPerformed(evt);
            }
        });
        jPanelProducts.add(jbtnBottleOfPerfume, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 40));

        jbtnImportedBottleOfPerfume.setText("Bottle of Perfume ");
        jbtnImportedBottleOfPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImportedBottleOfPerfumeActionPerformed(evt);
            }
        });
        jPanelProducts.add(jbtnImportedBottleOfPerfume, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 190, 40));

        jbtnImportedHeadachePills.setText("Headache Pills ");
        jPanelProducts.add(jbtnImportedHeadachePills, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 170, 40));

        jbtnImportedOil.setText("Oil ");
        jPanelProducts.add(jbtnImportedOil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 190, 40));

        jbtnImportedColaBox.setText("Cola Box");
        jPanelProducts.add(jbtnImportedColaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 170, 40));

        jbtnImportedChocolateBox.setText("Chocolate Box ");
        jPanelProducts.add(jbtnImportedChocolateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 190, 40));

        jbtnImportedBooks.setText("Books ");
        jPanelProducts.add(jbtnImportedBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 190, 40));

        jLabelImportedGoods.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelImportedGoods.setText("Imported Goods");
        jPanelProducts.add(jLabelImportedGoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        getContentPane().add(jPanelProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 600, 330));

        jTableReceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTableReceipt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 300, 330));

        jPanelOperation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanelOperation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanelOperation.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 210, 40));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanelOperation.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 210, 40));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanelOperation.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 40));

        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove ");
        jbtnRemove.setToolTipText("");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanelOperation.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 320, 40));

        getContentPane().add(jPanelOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 600, 110));

        jPanelResult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanelResult.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotal.setText("Total");
        jPanelResult.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 40));

        jLabelSalesTaxes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSalesTaxes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalesTaxes.setText("Sales Taxes");
        jPanelResult.add(jLabelSalesTaxes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        jTextFieldTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelResult.add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 140, 30));

        jTextFieldSalesTax.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldSalesTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSalesTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalesTaxActionPerformed(evt);
            }
        });
        jPanelResult.add(jTextFieldSalesTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 140, 30));

        getContentPane().add(jPanelResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 300, 110));

        jLabelReceipt.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelReceipt.setForeground(new java.awt.Color(51, 153, 255));
        jLabelReceipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReceipt.setText("Receipt");
        getContentPane().add(jLabelReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 150, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
               this.dispose();      //close window                    
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jTextFieldSalesTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalesTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalesTaxActionPerformed

    private void jbtnCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCDActionPerformed

    private void jbtnColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnColaActionPerformed

    private void jbtnColaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnColaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnColaBoxActionPerformed

    private void jbtnBottleOfPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBottleOfPerfumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBottleOfPerfumeActionPerformed

    private void jbtnImportedBottleOfPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImportedBottleOfPerfumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnImportedBottleOfPerfumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

        //create dataBase : goods_db if it is not exist
        //initialization function
    public static void CreateDb() {
        String url = "jdbc:mysql://localhost";
        String username = "root";
        String password = "root";
        String sql = "CREATE DATABASE IF NOT EXISTS goods_db";

        try (Connection conn = DriverManager.getConnection(url, username, password);
                PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.execute();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
    
        //create table : goods if it is not exist
        //initialization function
    public static void Create_goods_table() {

        String DB_URL = "jdbc:mysql://localhost/goods_db";
        String USER = "root";
        String PASS = "root";
        // Open a connection
        try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
                Statement stmt = conn.createStatement();) {
            String sql = "CREATE TABLE IF NOT EXISTS goods "
                    + "(id int NOT NULL AUTO_INCREMENT, "
                    + " name varchar(35) NOT NULL, "
                    + " price float NOT NULL, "
                    + " tax_class varchar(35) DEFAULT NULL, "
                    + " PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3";

            stmt.executeUpdate(sql);
            System.out.println("the table goodds has been created successfully...");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
       public static void initialize_goods_table() {
        String[] names = {"Chocolate Bar", "Book", "CD", "Chocolate Box", "Oil", "Cola", "Bottle of Perfume", "Headache Pills", "Cola Box", "Bottle of Perfume", "Headache Pills ", "Oil", "Chocolate Box", "Cola Box", "Books"};
        float[] prices = {10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12};
        String[] tax_classes = {"free_tax", "internal", "internal", "internal", "internal", "internal", "internal", "internal", "internal", "imported", "imported", "imported", "imported", "imported", "imported"};
        
        String DB_URL = "jdbc:mysql://localhost/goods_db";
        String USER = "root";
        String PASS = "root";
        boolean resault = check_if_empty_goods_table();
        
        if (resault) {
            Connection con;
            PreparedStatement pst;
            String sql = "INSERT INTO goods "
                    + "( name , price , tax_class)"
                    + "VALUES(? , ? , ?)";
            for (int i = 0; i < names.length; i++) {
                try {
                    con = DriverManager.getConnection(DB_URL, USER, PASS);
                    pst = con.prepareStatement(sql);

                    pst.setString(1, names[i]);
                    pst.setFloat(2, prices[i]);
                    pst.setString(3, tax_classes[i]);
                    pst.executeUpdate();

                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
  public static boolean check_if_empty_goods_table(){
              boolean res = false;
        String DB_URL = "jdbc:mysql://localhost/goods_db";
        String USER = "root";
        String PASS = "root";
        Connection con;
        PreparedStatement pst;
        ResultSet rst;
        try {
            con = (Connection) DriverManager.getConnection(DB_URL, USER, PASS);
            String sql = "SELECT * FROM goods";
            pst = con.prepareStatement(sql);
            rst = pst.executeQuery();

            if (rst.next()) { // check if exist more at least one row
                res = false;
            } else {
                res = true;
            }

        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        return res;
  
  }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImportedGoods;
    private javax.swing.JLabel jLabelReceipt;
    private javax.swing.JLabel jLabelSalesTaxes;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelOperation;
    private javax.swing.JPanel jPanelProducts;
    private javax.swing.JPanel jPanelResult;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReceipt;
    private javax.swing.JTextField jTextFieldSalesTax;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JButton jbtnBook;
    private javax.swing.JButton jbtnBottleOfPerfume;
    private javax.swing.JButton jbtnCD;
    private javax.swing.JButton jbtnChocolateBar;
    private javax.swing.JButton jbtnChocolateBox;
    private javax.swing.JButton jbtnCola;
    private javax.swing.JButton jbtnColaBox;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnHeadachePills;
    private javax.swing.JButton jbtnImportedBooks;
    private javax.swing.JButton jbtnImportedBottleOfPerfume;
    private javax.swing.JButton jbtnImportedChocolateBox;
    private javax.swing.JButton jbtnImportedColaBox;
    private javax.swing.JButton jbtnImportedHeadachePills;
    private javax.swing.JButton jbtnImportedOil;
    private javax.swing.JButton jbtnOil;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    // End of variables declaration//GEN-END:variables
}
