
import java.util.List;



/**
 *
 * @author moham
 */
public class Printing extends javax.swing.JFrame {

    
    public Printing() {
      
    }
    List<String> names_temp;
    List<Integer> quantity_temp;
    List<Float> prices_temp;

    

    public Printing(List<String> names_temp, List<Integer> quantity_temp, List<Float> prices_temp) {
        initComponents();
        
        this.names_temp = names_temp;
        this.quantity_temp = quantity_temp;
        this.prices_temp = prices_temp;

        loop_on_products();
    }

    public void loop_on_products() {
        for (int i = 0; i < names_temp.size(); i++) {
            String p_name = names_temp.get(i);
            int p_quantity = quantity_temp.get(i);
            Float p_price = prices_temp.get(i);

            int ind = get_id(Main.names, p_name);

            float tax_value = 0;
            if (Main.tax_classes[ind].equals("internal")) {
                tax_value = 0.1f;
            } else if (Main.tax_classes[ind].equals("imported")) {
                tax_value = 0.05f;
            } else if (Main.tax_classes[ind].equals("internal_imported")) {
                tax_value = 0.15f;
            } else if (Main.tax_classes[ind].equals("free_tax")) {
                tax_value = 0.0f;
            }
            float p_final_price = p_price * p_quantity + p_price * p_quantity * tax_value;
            jTextArea1.append("name : " + p_name + " quantity : " + p_quantity + " price with tax : " + p_final_price + "\n");
        }
    }

    public int get_id(String names[], String name) {
        for (int i = 0; i < names.length; i++) {
            if (name.equals(names[i])) {
                return i;
            }

        }
        return -1;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Printing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Printing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Printing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Printing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Printing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
